### ISSUE TITLE
Tweak docker-sync?

### ISSUE THREAD

**Issue by civilcode-pairing** [civilcode/acme-platform#147]
Issues we are facing right now:

- Touching a file (no modification) does not trigger mix test.watch
- Sometimes, the CPU goes 100%. I had to stop, clean and start (HF)
- TBD

**Comment by frahugo** [comment]
Based on https://docker-sync.readthedocs.io/en/latest/advanced/how-it-works.html#native-osx-in-depth, I enabled monit locally to see if it helps the 100% CPU usage.

```
version: "2"

options:
  verbose: false
syncs:
  source_code:
    src: '.'
    sync_excludes: ['.git', '_build', 'deps', 'apps/gccg_web/assets/node_modules', 'apps/gccg_web/priv/static']
    monit_enable: true
    monit_interval: 5
    monit_high_cpu_cycles: 2

```
